# .github/workflows/dependency-graph.yml
name: Update Dependency Graph
on:
  push:
    branches:
      - master # default branch of the project
jobs:
  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-24.04 # noble
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: sbt/setup-sbt@234370af1319038bf8dc432f8a7e4b83078a1781 # v1.1.11
      - uses: scalacenter/sbt-dependency-submission@f43202114d7522a4b233e052f82c2eea8d658134 # v3.2.1
        env:
          JFROG_USERNAME: ${{ secrets.ARTIFACTORY_READONLY_TOKEN_USER }}
          JFROG_PASSWORD: ${{ secrets.ARTIFACTORY_READONLY_TOKEN }}
